apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
  namespace: dockercoins
spec:
  selector:
    matchLabels:
      app: hasher
  template:
    spec:
      containers:
        - name: hasher
          image: dockercoins/hasher:v0.1
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
  namespace: dockercoins
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80