apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: dockercoins
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dockercoins
spec:
  type: ClusterIP
  ports:
    - port: 6379
      name: http
      protocol: TCP
      targetPort: 80