apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: dockercoins
spec:
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: rng
          image: dockercoins/webui:v0.1
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: dockercoins
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80