apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: dockercoins
spec:
  selector:
    matchLabels:
      app: worker
  template:
    spec:
      containers:
        - name: worker
          image: dockercoins/worker:v0.1
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: dockercoins
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80